#!/bin/bash

echo "
 _  _ ___ ___    _  _  ___  ___ _____
| || |_  ) _ \  | || |/ _ \/ __|_   _|
| __ |/ / (_) | | __ | (_) \__ \ | |
|_||_/___\___/  |_||_|\___/|___/ |_|

"

# Change dir to the script location so that it can be called from any path,
# e.g. from cron.
cd `dirname $0`

# Generate random data
python3 data.py

# Kill previous running node process. Node this could have wider impact - it will
# kill all processes with this name.
pkill "node host"

# Delete OrbitDB data so H2O-Host will load only the newly generated data.
rm -rf orbitdb

# Start H2O-Host
timeout 15s node host
