#!/bin/bash

echo "
 _  _ ___ ___    _  _  ___  ___ _____
| || |_  ) _ \  | || |/ _ \/ __|_   _|
| __ |/ / (_) | | __ | (_) \__ \ | |
|_||_/___\___/  |_||_|\___/|___/ |_|

"

while [ true ]
do
    pkill "node host"
    python3 data.py && timeout 15s node host
done
